name: Semantic PR Title

on:
  pull_request_target:
    types: 
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  lint-pr-title:
    uses: ./.github/workflows/reusable-semantic-pr-title.yaml
    permissions:
      pull-requests: write
      statuses: write
  lint-yaml:
    - uses: actions/checkout@v3
    - name: YAML Lint
      uses: ibiqlik/action-yamllint@v3.1.1
      with:
        config_file: .github/.yamllint.yml
