name: PR Checks

on:
  pull_request_target:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  lint-pr-title:
    uses: ./.github/workflows/reusable-semantic-pr-title.yaml
    permissions:
      pull-requests: write
      statuses: write
  lint-yaml:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v7
      - name: YAML Lint
        uses: ibiqlik/action-yamllint@2576378a8e339169678f9939646ee3ee325e845c # v3.1.1
        with:
          config_file: .github/.yamllint.yml
