name: Semantic PR Title

on:
  workflow_call:
    inputs:
      types:
        description: "The allowed commit types"
        required: false
        type: string
        default: |
          feat
          fix
          docs
          style
          refactor
          perf
          test
          chore
          build
          ci
      requireScope:
        description: "Whether a scope is required"
        required: false
        type: boolean
        default: true
      scopes:
        description: "The allowed commit scopes"
        required: false
        type: string
        default: ""
      subjectPattern:
        description: "The regex pattern for the subject"
        required: false
        type: string
        default: "^#[0-9]+.*$"
      exampleCommitTitle:
        description: "An example of a valid commit title"
        required: false
        type: string
        default: "feat(ci): #1234 add new feature"

permissions:
  contents: read
  pull-requests: write
  statuses: write

jobs:
  lint-pr-title:
    name: Lint PR title
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v7

      - uses: ./.github/actions/semantic-pull-request
        with:
          types: ${{ inputs.types }}
          requireScope: ${{ inputs.requireScope }}
          scopes: ${{ inputs.scopes }}
          subjectPattern: ${{ inputs.subjectPattern }}
          exampleCommitTitle: ${{ inputs.exampleCommitTitle }}
