name: YAML Lint

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - "**.yml"
      - "**.yaml"

concurrency:
  group: yaml-lint-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  lint-yaml:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v7

      - name: Get changed YAML files
        id: changed-files
        uses: tj-actions/changed-files@9426d40962ed5378910ee2e21d5f8c6fcbf2dd96 # v47.0.6
        with:
          files: |
            **/*.yml
            **/*.yaml

      - name: YAML Lint
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: ibiqlik/action-yamllint@2576378a8e339169678f9939646ee3ee325e845c # v3.1.1
        with:
          file_or_dir: ${{ steps.changed-files.outputs.all_changed_files }}
          config_file: .github/.yamllint.yml
          format: github
