name: YAML Lint

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - "**.yml"
      - "**.yaml"

concurrency:
  group: yaml-lint-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  lint-yaml:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v7
      - name: YAML Lint
        uses: ibiqlik/action-yamllint@2576378a8e339169678f9939646ee3ee325e845c # v3.1.1
        with:
          config_file: .github/.yamllint.yml
          format: github
