name: YAML Lint

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - "**.yml"
      - "**.yaml"

permissions: {}

concurrency:
  group: yaml-lint-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  lint-yaml:
    uses: ./.github/workflows/reusable-yaml-lint.yml
    permissions:
      contents: read  # the reusable's only need: checkout the YAML it lints
    with:
      config_file: .yamllint.yml
